### ISSUE TITLE
Error running deployment script - cosmosDeploy

### ISSUE THREAD

**Issue by mhodgson3** [OfficeDev/microsoft-teams-apps-callrecord-insights#26]
When running the deployment script I am getting an error on the cosmos part of the script.

BadRequest,"target":" /subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/CallRecordInsightsRG/providers/Microsoft.DocumentDB/databaseAccounts/callrecordinsightscdb", "message":"Dns record for callrecordinsightscdb under zone Document is already taken. Please use a different name for the account.

Any ideas?

Thanks

**Comment by adthom** [comment]
You will need to select a different base resource name when running the deployment script.
