### ISSUE TITLE
trouble deploying

### ISSUE THREAD

**Issue by ysijason** [OfficeDev/microsoft-teams-apps-callrecord-insights#33]
hi there, assume this is on our end, but having some trouble deploying the function app. any guidance? wonder if its a timeout thing.

Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/cosmosDeploy is Running.
Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/kustoDeploy is Running.
Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/functionDeploy is Running.
Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/cosmosDeploy has Succeeded.
**Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/functionDeploy has Failed.**
WARNING: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/kustoConfigure is Running.
Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/kustoDeploy has Succeeded.
Solution deployment is failed.
Deploy Resource: subscriptions/xxx/resourceGroups/callRecordsRG/providers/Microsoft.Resources/deployments/kustoConfigure has Succeeded.
deployifneeded : Solution deployment in resource group 'callRecordsRG' failed. Please ensure you have access to the subscription and try again.
At C:\Users\Administrator\Downloads\microsoft-teams-apps-callrecord-insights-main\microsoft-teams-apps-callrecord-insights-main\deploy\deploy.ps1:402 char:15
+ $Deployment = deployifneeded 'Solution' deploy (@{
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,deployifneeded

**Comment by ysijason** [comment]
ran with -Verbose 

**.\deploy.ps1 @DeploymentParameters -Verbose**

and reviewed activity logs 

**https://portal.azure.com/#view/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/~/activityLog**

Error code
VaultAlreadyExists
Message
The vault name 'gkvcallRecords' is already in use. Vault names are globally unique so it is possible that the name is already taken. If you are sure that the vault name was not taken then it is possible that a vault with the same name was recently deleted but not purged after being placed in a recoverable state. If the vault is in a recoverable state then the vault will need to be purged before reusing the name. For more information about VaultAlreadyExists, soft delete and purging a vault follow this link https://go.microsoft.com/fwlink/?linkid=2147740.

ended up having to rename keyvaultName in deployFunction.bicep. 

my guess is some timing issue and had to rerun. 

maybe update script to support an existing key vault

**Comment by cdhayward** [comment]
I had the same issue.  You need to ensure **BaseResourceName** is globally unique. I originally used Teams-CRI and it failed. I assume someone else has used it.
