### ISSUE TITLE
GCC High Support

### ISSUE THREAD

**Issue by bbradleyg12** [OfficeDev/microsoft-teams-apps-callrecord-insights#34]
We are working on deploying this in GCC High but seems the graph api is only supporting/referencing commercial (graph.microsoft.com vs graph.microsoft.us)

Is there any reason this project could not be branched or modified to support GCC High?

**Comment by adthom** [comment]
I am actually actively working on adding GCC High support, just finishing some testing steps before we release an update including those minor changes.

**Comment by nathan-short** [comment]
Andi,

Thanks for the update. I’ve CCed my people so they know.

Thanks,

***@***.***<https://materion.com/>
Nathan Short
System Analyst I
p: +1.216.383.4020
e: ***@***.******@***.***>
Materion Corporation
6070 Parkland Blvd
Mayfield Heights, OH 44124
materion.com<https://materion.com/>
Service Desk
p: 216.383.4000 ext 104000
e: ***@***.******@***.***>

***@***.***
www.linkedin.com/nathan-short69a014193/<http://www.linkedin.com/nathan-short69a014193/>

[Logo, company name  Description automatically generated]<https://www.credly.com/badges/da427468-417d-4831-bdce-a43c4b3e12a4/public_url>[Logo  Description automatically generated]<https://www.credly.com/badges/759f7460-78e9-4985-a5ea-acec5d8e624d/public_url>[Logo, company name  Description automatically generated]<https://www.credly.com/badges/36b0a7ae-f17d-450b-96a6-86bf64db0525/public_url>
[A red and white logo  Description automatically generated with low confidence]<https://www.credly.com/badges/b57d1101-8e90-480f-b3e1-a58b0ad91114/public_url>[Logo, company name  Description automatically generated]<https://www.credly.com/badges/5498d609-74c7-4fa2-bad8-4a31f87d14a5/public_url>[Logo, company name  Description automatically generated]<https://www.credly.com/badges/387d20d7-cc84-454f-8fb2-1427ca8e9de7/public_url>
***@***.******@***.***<https://www.credly.com/badges/05632c65-ed63-4891-836c-74d5dc05b2d9/public_url>
