### ISSUE TITLE
Deploy successful - No data

### ISSUE THREAD

**Issue by cdhayward** [OfficeDev/microsoft-teams-apps-callrecord-insights#35]
Hello,

The script successfully deploys, however I don't get any data.

When running verification after deploying script:

_$HealthState

healthy           : True
eventHub          : @{healthy=True; status=; url=sb://Teams-CRIxxxxx.servicebus.windows.net/graphevents}
cosmos            : @{healthy=True; status=;
                    url=https://teams-crixxxxxcdb.documents.azure.com:443/dbs/callrecordinsights/colls/records}
downloadQueue     : @{healthy=True; status=;
                    url=https://callqt5pxxxxxxxxxx.queue.core.windows.net/callrecordinsightsdownload}
subscriptions     : {@{id=4b54c22e-9a36-42a0-9c77-xxxxxxxxxxxx; expirationDateTime=02/08/2024 07:56:05;
                    tenantId=d5fc2f10-69a4-4853-8005-xxxxxxxxxxxx}}
unhealthyServices : {}_

Cosmos DB Data connections looks good.

When I open https://developer.microsoft.com/en-us/graph/graph-explorer and run a GET v1.0 at **https://graph.microsoft.com/v1.0/subscriptions**

It only returns:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions",
    "@microsoft.graph.tips": "Use $select to choose only the properties your app needs, as this can lead to performance improvements. For example: GET subscriptions?$select=applicationId,changeType",
    "value": []
}

How are the values populated?  Should the deploy.ps1 script do it?  I'm basing what I should see off: https://github.com/OfficeDev/microsoft-teams-apps-callrecord-insights/wiki/Deployment#deployment-validation--verification

**Comment by adthom** [comment]
Hi, can you check 2 things for me?
For the Graph Explorer query you ran, did you run that for the Entra tenant where the application is deployed (d5fc2f10-69a4-4853-8005-xxxxxxxxxxxx)? The application is configured to use a managed identity in the host Entra tenant, and thus is what is configured for notifications. 
Do you see calls show up in Teams Admin Center for the expected users?

**Comment by cdhayward** [comment]
Hi Andy,

This was in a lab tenant, I've noticed today data is now being logged.

Turns out I needed to consent to permissions to Subscription.Read.All in Graph Explorer whilst logged in as GA!

Thanks for getting back to me.

**Comment by adthom** [comment]
Glad to hear it is all flowing now.
